# some more ls aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias vd='vim ~/code/mdwiki/daily.md'
alias vw='vim ~/code/mdwiki/wishlist.md'
alias gac='git add . ; git commit -m Updates'
alias gss='git status'
alias gp='git push'
